//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CII.LAR.Res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LaserAlignment {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LaserAlignment() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cii.Lar.Res.LaserAlignment", typeof(LaserAlignment).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Laser.
        /// </summary>
        internal static string StrAlignLaser {
            get {
                return ResourceManager.GetString("StrAlignLaser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string StrFinish {
            get {
                return ResourceManager.GetString("StrFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string StrNext {
            get {
                return ResourceManager.GetString("StrNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Remove any embryos from the  field of view.
        ///
        ///Place an empty Petri dish or slide onto the microscope stage..
        /// </summary>
        internal static string StrPreSet0 {
            get {
                return ResourceManager.GetString("StrPreSet0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pilot is now switched on. Adjust the focus if necessary so that the Pilot laser spot appears as small as possible on the monitor.
        ///If the red spot appears too faint then reduce the intensity of the illumination or adjust the brightness of the pilot laser using the rear panel control.
        ///Click the pilot laser on screen..
        /// </summary>
        internal static string StrPreSet1 {
            get {
                return ResourceManager.GetString("StrPreSet1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string StrSave {
            get {
                return ResourceManager.GetString("StrSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Calibration of the laser has now been complete.
        ///
        ///Click Finish to save the calibration..
        /// </summary>
        internal static string StrStepComplete {
            get {
                return ResourceManager.GetString("StrStepComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///The pilot laser has moved.
        ///
        ///Click the centre of the pilot laser on screen..
        /// </summary>
        internal static string StrStepFive {
            get {
                return ResourceManager.GetString("StrStepFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///The pilot laser has moved.
        ///
        ///Click the centre of the pilot laser on screen..
        /// </summary>
        internal static string StrStepFour {
            get {
                return ResourceManager.GetString("StrStepFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pilot laser is in position whitch should be visible on the screen.
        ///Check you can see the pilot laser on screen.
        ///Adjust the focus if necessary so that the Pilot laser spot appears as small as possible on the monitor.
        ///If the red spot appears too faint then reduce the intensity of the illumination or adjust the brightness of the pilot laser using the rear panel control.
        ///Click the pilot laser on screen..
        /// </summary>
        internal static string StrStepOne {
            get {
                return ResourceManager.GetString("StrStepOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///The pilot laser has moved.
        ///
        ///Click the centre of the pilot laser on screen..
        /// </summary>
        internal static string StrStepSeven {
            get {
                return ResourceManager.GetString("StrStepSeven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///The pilot laser has moved.
        ///
        ///Click the centre of the pilot laser on screen..
        /// </summary>
        internal static string StrStepSix {
            get {
                return ResourceManager.GetString("StrStepSix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///The pilot laser has now moved by a small amount.
        ///
        ///Click the centre of the pilot laser on screen..
        /// </summary>
        internal static string StrStepThree {
            get {
                return ResourceManager.GetString("StrStepThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laser Target Alignment - Step Complete.
        /// </summary>
        internal static string StrStepTitleComplete {
            get {
                return ResourceManager.GetString("StrStepTitleComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laser Target Alignment - Step Five.
        /// </summary>
        internal static string StrStepTitleFive {
            get {
                return ResourceManager.GetString("StrStepTitleFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laser Target Alignment - Step Four.
        /// </summary>
        internal static string StrStepTitleFour {
            get {
                return ResourceManager.GetString("StrStepTitleFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laser Target Alignment - Step One.
        /// </summary>
        internal static string StrStepTitleOne {
            get {
                return ResourceManager.GetString("StrStepTitleOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laser Target Alignment - Step Seven.
        /// </summary>
        internal static string StrStepTitleSeven {
            get {
                return ResourceManager.GetString("StrStepTitleSeven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laser Target Alignment - Step Six.
        /// </summary>
        internal static string StrStepTitleSix {
            get {
                return ResourceManager.GetString("StrStepTitleSix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laser Target Alignment - Step Three.
        /// </summary>
        internal static string StrStepTitleThree {
            get {
                return ResourceManager.GetString("StrStepTitleThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laser Target Alignment - Step Two.
        /// </summary>
        internal static string StrStepTitleTwo {
            get {
                return ResourceManager.GetString("StrStepTitleTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///The pilot laser has now moved by a small amount.
        ///
        ///Click the centre of the pilot laser on screen..
        /// </summary>
        internal static string StrStepTwo {
            get {
                return ResourceManager.GetString("StrStepTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laser Target Alignment.
        /// </summary>
        internal static string StrTitle {
            get {
                return ResourceManager.GetString("StrTitle", resourceCulture);
            }
        }
    }
}
