//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CII.LAR.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CII.LAR.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap about
        {
            get
            {
                object obj = ResourceManager.GetObject("about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap assign {
            get {
                object obj = ResourceManager.GetObject("assign", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap assigned {
            get {
                object obj = ResourceManager.GetObject("assigned", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap backflush {
            get {
                object obj = ResourceManager.GetObject("backflush", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap camera {
            get {
                object obj = ResourceManager.GetObject("camera", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap capture {
            get {
                object obj = ResourceManager.GetObject("capture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap copy {
            get {
                object obj = ResourceManager.GetObject("copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Del {
            get {
                object obj = ResourceManager.GetObject("Del", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap detail {
            get {
                object obj = ResourceManager.GetObject("detail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap down {
            get {
                object obj = ResourceManager.GetObject("down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap elliptical {
            get {
                object obj = ResourceManager.GetObject("elliptical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap files {
            get {
                object obj = ResourceManager.GetObject("files", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap flip {
            get {
                object obj = ResourceManager.GetObject("flip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap hand {
            get {
                object obj = ResourceManager.GetObject("hand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap idscamera {
            get {
                object obj = ResourceManager.GetObject("idscamera", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap idscamera1 {
            get {
                object obj = ResourceManager.GetObject("idscamera1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Ready 的本地化字符串。
        /// </summary>
        internal static string labelItem1Str {
            get {
                return ResourceManager.GetString("labelItem1Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        internal static string labelItemLanguageStr {
            get {
                return ResourceManager.GetString("labelItemLanguageStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap laser {
            get {
                object obj = ResourceManager.GetObject("laser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap line {
            get {
                object obj = ResourceManager.GetObject("line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap open {
            get {
                object obj = ResourceManager.GetObject("open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] PingFang_Medium {
            get {
                object obj = ResourceManager.GetObject("PingFang_Medium", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap polygon {
            get {
                object obj = ResourceManager.GetObject("polygon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap port {
            get {
                object obj = ResourceManager.GetObject("port", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap print {
            get {
                object obj = ResourceManager.GetObject("print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap print_preview {
            get {
                object obj = ResourceManager.GetObject("print preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap rectangular {
            get {
                object obj = ResourceManager.GetObject("rectangular", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Roboto_Medium {
            get {
                object obj = ResourceManager.GetObject("Roboto_Medium", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Roboto_Regular {
            get {
                object obj = ResourceManager.GetObject("Roboto_Regular", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ruler {
            get {
                object obj = ResourceManager.GetObject("ruler", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap setting {
            get {
                object obj = ResourceManager.GetObject("setting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Stop {
            get {
                object obj = ResourceManager.GetObject("Stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Close Simulator 的本地化字符串。
        /// </summary>
        internal static string StrCloseSimulator {
            get {
                return ResourceManager.GetString("StrCloseSimulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click Report to create a Technical Support Request. 的本地化字符串。
        /// </summary>
        internal static string StrCreateReport {
            get {
                return ResourceManager.GetString("StrCreateReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you confirm to delete the file ? 的本地化字符串。
        /// </summary>
        internal static string StrDeleteFile {
            get {
                return ResourceManager.GetString("StrDeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Laser Target Alignment 的本地化字符串。
        /// </summary>
        internal static string StrLaserAlignmentTitle {
            get {
                return ResourceManager.GetString("StrLaserAlignmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Laser Appearance 的本地化字符串。
        /// </summary>
        internal static string StrLaserAppearanceTitle {
            get {
                return ResourceManager.GetString("StrLaserAppearanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Laser Control 的本地化字符串。
        /// </summary>
        internal static string StrLaserCtrlTitle {
            get {
                return ResourceManager.GetString("StrLaserCtrlTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        internal static string StrAboutCtrlTitle
        {
            get
            {
                return ResourceManager.GetString("StrAboutCtrlTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 company 的本地化字符串。
        /// </summary>
        internal static System.Drawing.Bitmap company
        {
            get
            {
                object obj = ResourceManager.GetObject("company", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找类似 Laser Hole Size Calibration 的本地化字符串。
        /// </summary>
        internal static string StrLaserHoleSizeCalibration {
            get {
                return ResourceManager.GetString("StrLaserHoleSizeCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input a number lense factor. 的本地化字符串。
        /// </summary>
        internal static string StrLenseFactorInputError {
            get {
                return ResourceManager.GetString("StrLenseFactorInputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Object Lense Manager 的本地化字符串。
        /// </summary>
        internal static string StrObjectLense {
            get {
                return ResourceManager.GetString("StrObjectLense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string StrOK {
            get {
                return ResourceManager.GetString("StrOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Turn On Simulator 的本地化字符串。
        /// </summary>
        internal static string StrOpenSimulator {
            get {
                return ResourceManager.GetString("StrOpenSimulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Program may run out of memory, please restart the program. 的本地化字符串。
        /// </summary>
        internal static string StrOutOfMemory {
            get {
                return ResourceManager.GetString("StrOutOfMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Report 的本地化字符串。
        /// </summary>
        internal static string StrReport {
            get {
                return ResourceManager.GetString("StrReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ruler Appearance 的本地化字符串。
        /// </summary>
        internal static string StrRulerAppearanceTitle {
            get {
                return ResourceManager.GetString("StrRulerAppearanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scale Appearance 的本地化字符串。
        /// </summary>
        internal static string StrScaleAppearanceTitle {
            get {
                return ResourceManager.GetString("StrScaleAppearanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setting 的本地化字符串。
        /// </summary>
        internal static string StrSetting {
            get {
                return ResourceManager.GetString("StrSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keyboard Shortcut Configuration 的本地化字符串。
        /// </summary>
        internal static string StrShortcutTitle {
            get {
                return ResourceManager.GetString("StrShortcutTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Keyboard Shortcut Configuration 的本地化字符串。
        /// </summary>
        internal static string StrShortcutExist
        {
            get
            {
                return ResourceManager.GetString("StrShortcutExist", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Statistics Information 的本地化字符串。
        /// </summary>
        internal static string StrStatisticsTitle {
            get {
                return ResourceManager.GetString("StrStatisticsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Encountered an unknown error. Please restart the program. 的本地化字符串。
        /// </summary>
        internal static string StrUnknownErrorMsg {
            get {
                return ResourceManager.GetString("StrUnknownErrorMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap add
        {
            get
            {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap sub
        {
            get
            {
                object obj = ResourceManager.GetObject("sub", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap undo {
            get {
                object obj = ResourceManager.GetObject("undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap unit {
            get {
                object obj = ResourceManager.GetObject("unit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap up {
            get {
                object obj = ResourceManager.GetObject("up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap video {
            get {
                object obj = ResourceManager.GetObject("video", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap zoom {
            get {
                object obj = ResourceManager.GetObject("zoom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Zoom_in {
            get {
                object obj = ResourceManager.GetObject("Zoom in", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Zoom_out {
            get {
                object obj = ResourceManager.GetObject("Zoom out", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap zoomFit {
            get {
                object obj = ResourceManager.GetObject("zoomFit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        /// <summary>
        ///   查找类似 Camera choose 的本地化字符串。
        /// </summary>
        internal static string StrVideoChooseTitle
        {
            get
            {
                return ResourceManager.GetString("StrVideoChooseTitle", resourceCulture);
            }
        }
		/// <summary>
        ///   查找类似 Camera Available 的本地化字符串。
        /// </summary>
        internal static string StrVideoAvailable
        {
            get
            {
                return ResourceManager.GetString("StrVideoAvailable", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 No Camera Available 的本地化字符串。
        /// </summary>
        internal static string StrVideoNoAvailable
        {
            get
            {
                return ResourceManager.GetString("StrVideoNoAvailable", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Screenshot success 的本地化字符串。
        /// </summary>
        internal static string StrScreenshotSuccess
        {
            get
            {
                return ResourceManager.GetString("StrScreenshotSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Calibration success 的本地化字符串。
        /// </summary>
        internal static string StrCalibrationSuccess
        {
            get
            {
                return ResourceManager.GetString("StrCalibrationSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap warn
        {
            get
            {
                object obj = ResourceManager.GetObject("warn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找类似 Zoom Rate 的本地化字符串。
        /// </summary>
        internal static string StrZoomRate
        {
            get
            {
                return ResourceManager.GetString("StrZoomRate", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Waring 的本地化字符串。
        /// </summary>
        internal static string StrWarning
        {
            get
            {
                return ResourceManager.GetString("StrWarning", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Program Exist 的本地化字符串。
        /// </summary>
        internal static string StrProgramExit
        {
            get
            {
                return ResourceManager.GetString("StrProgramExit", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Hide Ruler的本地化字符串。
        /// </summary>
        internal static string StrHideRuler
        {
            get
            {
                return ResourceManager.GetString("StrHideRuler", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Single-hole 的本地化字符串。
        /// </summary>
        internal static string StrSingleHole
        {
            get
            {
                return ResourceManager.GetString("StrSingleHole", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Multi-hole 的本地化字符串。
        /// </summary>
        internal static string StrMultiHole
        {
            get
            {
                return ResourceManager.GetString("StrMultiHole", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 System Information 的本地化字符串。
        /// </summary>
        internal static string StrSystemInfoTitle
        {
            get
            {
                return ResourceManager.GetString("StrSystemInfoTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Disconnect 的本地化字符串。
        /// </summary>
        internal static string StrDisconnect
        {
            get
            {
                return ResourceManager.GetString("StrDisconnect", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Connected 的本地化字符串。
        /// </summary>
        internal static string StrConnected
        {
            get
            {
                return ResourceManager.GetString("StrConnected", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        internal static string StrYes
        {
            get
            {
                return ResourceManager.GetString("StrYes", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        internal static string StrNo
        {
            get
            {
                return ResourceManager.GetString("StrNo", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Abort 的本地化字符串。
        /// </summary>
        internal static string StrAbort
        {
            get
            {
                return ResourceManager.GetString("StrAbort", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Retry 的本地化字符串。
        /// </summary>
        internal static string StrRetry
        {
            get
            {
                return ResourceManager.GetString("StrRetry", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string StrCancel
        {
            get
            {
                return ResourceManager.GetString("StrCancel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Ignore 的本地化字符串。
        /// </summary>
        internal static string StrIgnore
        {
            get
            {
                return ResourceManager.GetString("StrIgnore", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        internal static string StrWaring
        {
            get
            {
                return ResourceManager.GetString("StrWaring", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        internal static string StrExit
        {
            get
            {
                return ResourceManager.GetString("StrExit", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Can not print video file! 的本地化字符串。
        /// </summary>
        internal static string StrCannotPrint
        {
            get
            {
                return ResourceManager.GetString("StrCannotPrint", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Can not print empty file 的本地化字符串。
        /// </summary>
        internal static string StrCannotPrintEmpty
        {
            get
            {
                return ResourceManager.GetString("StrCannotPrintEmpty", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Exit Msg的本地化字符串。
        /// </summary>
        internal static string StrExitMsg
        {
            get
            {
                return ResourceManager.GetString("StrExitMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The software is calibrating. If you are forced to quit, please turn off the calibration window first. 的本地化字符串。
        /// </summary>
        internal static string StrExitExceptionMsg
        {
            get
            {
                return ResourceManager.GetString("StrExitExceptionMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 StrMainTitle的本地化字符串。
        /// </summary>
        internal static string StrMainTitle
        {
            get
            {
                return ResourceManager.GetString("StrMainTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Enable Red Laser 的本地化字符串。
        /// </summary>
        internal static string StrEnableRedLaser
        {
            get
            {
                return ResourceManager.GetString("StrEnableRedLaser", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Close Red Laser 的本地化字符串。
        /// </summary>
        internal static string StrCloseRedLaser
        {
            get
            {
                return ResourceManager.GetString("StrCloseRedLaser", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Please wait for the laser serial port to be initialized and start calibration again. 的本地化字符串。
        /// </summary>
        internal static string StrLaserNotConnect
        {
            get
            {
                return ResourceManager.GetString("StrLaserNotConnect", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 You have to specify a modifier like &apos;Control&apos;, &apos;Alt&apos; or &apos;Shift&apos;. 的本地化字符串。
        /// </summary>
        internal static string StrmodifierWarning
        {
            get
            {
                return ResourceManager.GetString("StrmodifierWarning", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Enter HotKey here 的本地化字符串。
        /// </summary>
        internal static string StrEnterHotKey
        {
            get
            {
                return ResourceManager.GetString("StrEnterHotKey", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Are you confirm to delete this file? 的本地化字符串。
        /// </summary>
        internal static string StrConfirmToDelete
        {
            get
            {
                return ResourceManager.GetString("StrConfirmToDelete", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Please wait for the laser serial port to be initialized and then your can open red laser. 的本地化字符串。
        /// </summary>
        internal static string StrLaserNotReady
        {
            get
            {
                return ResourceManager.GetString("StrLaserNotReady", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Can not enable red when active laser is working. 的本地化字符串。
        /// </summary>
        internal static string StrCannotEnableRedLaser
        {
            get
            {
                return ResourceManager.GetString("StrCannotEnableRedLaser", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 {0}Holes 的本地化字符串。
        /// </summary>
        internal static string StrHoleNumber
        {
            get
            {
                return ResourceManager.GetString("StrHoleNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 StrConfirmToSelect 的本地化字符串。
        /// </summary>
        internal static string StrConfirmToSelect
        {
            get
            {
                return ResourceManager.GetString("StrConfirmToSelect", resourceCulture);
            }
        }
    }
}
